### ISSUE TITLE
Filter by category

### ISSUE THREAD

**Issue by suhlig** [suhlig/concourse-rss-resource#1]
Enable filtering by category, so that the resource only triggers on new versions of a certain category.

It will probably be configured like this:

```yaml
resources:
  - name: postgres-release-versions
    type: rss-resource
    source:
      url: https://dl.dropboxusercontent.com/u/165087/example-releases.rss
      categories:
        - a
        - b
        - c
```

so that only items with category a, b __and__ c are considered.
